### ISSUE TITLE
Game crash on loading a new image

### ISSUE THREAD

**Issue by xenzer** [Sirspam/Nya#11]
no clue what happened, i was using local files and just pressed the good old nya button and crash. it was very tragic
[_latest.log](https://github.com/Sirspam/Nya/files/9410832/_latest.log)

**Comment by Sirspam** [comment]
This does sound utterly tragic, I'm so sorry that you had to experience this.

Would you mind sending that image0 (74).jpeg over?

**Comment by xenzer** [comment]
![image0 (74)](https://user-images.githubusercontent.com/74574555/186274863-2d24b03e-270f-487a-9fdd-be9c2cccec1a.jpeg)

**Comment by Sirspam** [comment]
banger image

**Comment by xenzer** [comment]
i know right

**Comment by Sirspam** [comment]
Is this issue recreatable for you?
From a whim the issue may be with BSML's image downscaling ~~which wouldn't be a surprise since I wrote it~~. Can't seem to recreate the crash myself though.

**Comment by xenzer** [comment]
nope, cant seem to recreate it either.

**Comment by Sirspam** [comment]
We'll just assume it was a one off quirky Unity moment since I cannot recreate it and this is the first time I've been told about this happening. 

Although do open up this issue again if crashes start happening frequently
