### ISSUE TITLE
NSFW calls to nekos.life doesn't change the image

### ISSUE THREAD

**Issue by SiameseDerp** [Sirspam/Nya#9]
**System Information**
Plugin Version: 0.2.3
Game Version: 1.18.3
ModAssistant Version: 1.1.26
OS: Windows 10 1909
HMD: Oculus Rift CV1
-vrmode oculus: No

**Nya Settings**

Floating Screens
- Detach Nya in the menu: ON
- Show Nya in the pause menu: ON
- Show Nya's movement handle; ON

API Settings
- API: nekos.life
- SFW endpoint: neko
- NSFW endpoint: lewd

Other
- Auto Nya wait time: 5
- Remember NSFW setting: ON
- Skip NSFW confirmation: ON

**Issue**
Enabling NSFW mode on Nya and pressing the Nya button while the API is set to nekos.life does not change the image, both with and without auto-nya.

**Steps To Reproduce**
1. Install plugin version 0.2.3
2. Launch Beat Saber
3. Open Nya settings, and set API to nekos.life
4. Set Nya mode to NSFW
5. Press Nya button

**Expected behavior**
The image should change to an NSFW image from nekos.life

**Log File**
[latest.log](https://github.com/Sirspam/Nya/files/8791834/latest.log)

**Comment by Sirspam** [comment]
Nekos.Life recently removed all of it's NSFW endpoints.
Nya has been updated for this change in the latest version

**Comment by SiameseDerp** [comment]
That makes sense, thank you for the quick response.
